name: floaties
title: Floaties
license: MIT
base: core24
version: '1.0.0'
summary: A secure and minimalist sticky note application.
description: |
  Floaties provides secure, encrypted, floating sticky notes for your desktop.
  Features built-in atomic database storage, easy migration across Linux and Windows PCs, and a minimalist UI.

contact: mailto:azil@tuta.io
website: https://github.com/azil-74/floaties
issues: https://github.com/azil-74/floaties/issues
source-code: https://github.com/azil-74/floaties
donation: https://therealazil.gumroad.com/l/vdsqh

grade: stable
confinement: strict

platforms:
  amd64:

parts:
  floaties:
    plugin: python
    source: .
    python-packages:
      - PyQt6
      - cryptography
    stage-packages:
      - libxcb-cursor0
      - libfontconfig1
      - libx11-6

  metadata:
    plugin: dump
    source: .
    organize:
      floaties.png: meta/gui/floaties.png
      floaties.desktop: meta/gui/floaties.desktop

apps:
  floaties:
    command: bin/python3 $SNAP/main.py
    extensions: [gnome]
    desktop: gui/floaties.desktop
    environment:
      QT_QPA_PLATFORM: xcb
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - x11
  